name: Dev - Build and Deploy

on:
  push:
    branches:
      - main
    tags: 
      - '*'

jobs:
  run_job: 
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
 
      - name: Set Environment variables
        run: | 
          echo "DLD_URL=${{ secrets.DLD_URL }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
  
      - name: Clean - Build - ETL - Test Dataset       
        run: |
          make all
