name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  run_job: 
    runs-on: ubuntu-latest
    env:
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set RELEASE_DATE
        shell: bash
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          ZENODO_TOKEN: ${{ vars.ZENODO_PAT }}
          DLD_URL: ${{ vars.DLD_URL }}

      - name: Generate Parquet Dataset       
        run: |
          make all
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "rent_contracts_${{ env.RELEASE_DATE }}"
          name: "Rent Contracts Release ${{ env.RELEASE_DATE }}"
          files: output/rent_contracts_${{ env.RELEASE_DATE }}.parquet
