name: Daily data crawling job

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
    run_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run crawler
              run: |
                python src/extract.py