name: Daily data crawling job

on: 
  schedule:
    - cron: '0 8 * * *' # Runs every Tuesday at 8 am UTC

jobs:
    run_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Install dependencies
              env:
                ZENODO_TOKEN: ${{ secrets.ZENODO_PAT }}
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python dld_rent_contracts/__init__.py
