name: Daily Data Mining Task

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
    run_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run crawler with environment variables
              env: 
                URL: ${{ env.URL }}
                MONGO_DATABASE_NAME: ${{ env.MONGO_DATABASE_NAME }}
                MONGO_DATABASE_URI: ${{ env.MONGO_DATABASE_URI }}
              run: |
                python src/extract.py
