name: Daily data crawling job

on: 
  schedule:
    # - cron: '0 7 * * 2' # Every Tuesday at 7:00 UTC
    - cron: '5 * * * *'

jobs:
    run_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                export ZENODO_TOKEN=${{ secrets.ZENODO_PAT }}
                python dld_rent_contracts/__init__.py
              env:
                ZENODO_PAT: ${{ secrets.ZENODO_PAT }}