name: Cron Job - Generate Parquet Dataset

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  run_job:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set RELEASE_DATE
        id: set_release_date
        shell: bash
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    
      - name: Set Environment variables
        run: |
          echo "ZENODO_TOKEN=${{ secrets.ZENODO_PAT }}" >> $GITHUB_ENV
          echo "DLD_URL=${{ secrets.DLD_URL }}" >> $GITHUB_ENV
    
      - name: Generate Parquet Dataset       
        run: |
          make all
          
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "rent_contracts_${{ steps.set_release_date.outputs.RELEASE_DATE }}"
          name: "Rent Contracts Release ${{ steps.set_release_date.outputs.RELEASE_DATE }}"
          files: |
            output/rent_contracts_${{ steps.set_release_date.outputs.RELEASE_DATE }}.parquet
            output/rent_contracts_${{ env.RELEASE_DATE }}.parquet