name: Cron Job - Generate Parquet Dataset

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  run_job:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - name: Set Environment variables
        run: |
          echo "DLD_URL=${{ secrets.DLD_URL }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
    
      - name: Generate Parquet Dataset       
        run: |
          make all

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Get File Name
        id: get_filename
        run: echo "filename=dld_rent_contracts_$(date +%Y-%m-%d).parquet" >> $GITHUB_ENV

      - name: Upload Parquet File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.filename }}
          asset_name: rent_contracts_${{ env.filename }}
          asset_content_type: application/octet-stream
