name: Daily data crawling job

on: 
  schedule:
    # - cron: '0 0 * * *'
    # - cron: '*/5 * * * *'
    - cron: '0 7 * * 2'

jobs:
    run_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run crawler with environment variables
              env: 
                URL: "https://huspy.com/api/v1/search?limit=5000&lastItemId="
                MONGO_DATABASE_NAME: "huspy"
                MONGO_DATABASE_URI: "mongodb+srv://realestate-analyzer:realestate-analyzer@cluster0.w0fxomx.mongodb.net/?retryWrites=true&w=majority"
              run: |
                python src/extract.py
